// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ucsxeefxgiudkkrphkye.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVjc3hlZWZ4Z2l1ZGtrcnBoa3llIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY4MzE3MzgsImV4cCI6MjA1MjQwNzczOH0.cYExqODziu4bHZ69QtJUX6rsL_2Psv68q3U8p3Su180";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);